CREATE TABLE users
	( id INTEGER PRIMARY KEY AUTOINCREMENT
	, display TEXT NOT NULL
	, login TEXT UNIQUE NOT NULL
	, shadow TEXT NOT NULL
	);

CREATE TABLE sessions
	( id INTEGER PRIMARY KEY AUTOINCREMENT
	, cookie TEXT UNIQUE NOT NULL
	, user_id INTEGER NOT NULL
	, FOREIGN KEY(user_id) REFERENCES users(id)
	);
